### PR TITLE
Allow Load Balancer for the replica's

### PR DESCRIPTION
**Pull request by feikesteenbergen**
By always creating a service for both the primary and replica's, and
optionally attaching a Load Balancer to the service we achieve that
there is always a service to connect to *from inside kubernetes*.
One service for the primary and one service for the replicas.

If the [replica]LoadBalancer is also enabled, than we will also expose a
LoadBalancer, which in an AWS scenario would become an ELB/NLB, which
would allow connections from outside the kubernetes cluster to the
database.

In passing, it seems we never use the `timescaledb` ep, better to remove
it then.

### CODE REVIEW

**Comment by iand** [comment]
What is the purpose of the headless service if it isn't connected to a load balancer?

**Comment by feikesteenbergen** [comment]
@iand 

> a cluster IP is not allocated, kube-proxy does not handle these Services, and there is no load balancing or proxying done by the platform for them.

https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

However, you can still use the service to connect, it is resolvable and will return the set of A records pointing to the pods that conform to the selector.

Example:
```
dig my-release-replica.feike.svc.cluster.local
```
```
;; ANSWER SECTION:
my-release-replica.feike.svc.cluster.local. 1 IN A 192.168.36.59
my-release-replica.feike.svc.cluster.local. 1 IN A 192.168.67.91
```

Which corresponds to the pods of the release:
```
kubectl get pods -o wide -L role
```
```
NAME                       READY   STATUS    RESTARTS   AGE    IP              [...]   ROLE
my-release-timescaledb-0   1/1     Running   0          118m   192.168.24.49   [...]   master
my-release-timescaledb-1   1/1     Running   0          118m   192.168.67.91   [...]   replica
my-release-timescaledb-2   1/1     Running   0          117m   192.168.36.59   [...]   replica
```

**Comment by iand** [comment]
@feikesteenbergen yes, but what is it's purpose? why do we need it?

**Comment by feikesteenbergen** [comment]
> why

well, we have customers asking for a way to connect to the replica's.
This gives them a way to connect to the replica's.

**Comment by iand** [comment]
ok, so it's to ensure that an endpoints resource is created that lists the replica IPs?

**Pull request merged**
