### PR TITLE
AWS_ROLE_ARN AWS_WEB_IDENTITY_TOKEN_FILE

### PR DESCRIPTION
**Pull request by mthoretton**
Don't unset `AWS_ROLE_ARN` `AWS_WEB_IDENTITY_TOKEN_FILE` env vars.
pgbackrest recently made possible to use web_identity to authenticate with AWS. In order to make it work those 2 variables have to be available in postgresql container.
See https://github.com/pgbackrest/pgbackrest/issues/1680
If you think it would make sense I could try to make this "vars filter" configurable in values.yml.

### CODE REVIEW

**Comment by sebastianvoss** [comment]
@mthoretton Thanks for this. I was facing this issue and your fix resolved it. Hopefully it gets merged soon so others can benefit.

**Comment by DevSusu** [comment]
@mthoretton thank you for the fix

**Review by paulfantom — APPROVED** [review]

**Comment by DevSusu** [comment]
@ayeks here's part of `values.yaml` I used. take a look into `pgbackrest` documentation for further investigation

```
  backup:
    enabled: true
    # https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-bucket
    # env variable that goes into pgbackrest container
    # used to saving backups to s3
    pgBackRest:
      compress-type: lz4
      process-max: 4
      repo1-type: s3
      # Number of differential backups to retain.
      repo1-retention-diff: 2
      # Number of full backups to retain.
      repo1-retention-full: 2
      repo1-cipher-type: "none"
      repo1-s3-bucket: <your-bucket-name>
      repo1-s3-region: <your-bucket-region>
      # Automatically retrieve web identity credentials
      # https://github.com/pgbackrest/pgbackrest/pull/1527#issue-1018748945
      repo1-s3-key-type: web-id
    jobs:
      - name: full-weekly
        type: full
        schedule: "12 02 * * 0"
      - name: incremental-daily
        type: incr
        schedule: "12 02 * * 1-6"
    env:
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::123456789123:role/<your-role-name>
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Comment by ayeks** [comment]
@DevSusu thanks a lot! I had an issue that the [service account token](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets) was not autogenerated which looks like a [change](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes) with k8s 1.24.

Here is my timescale values.yaml that enables the backup via IAM role of the service account:

```yaml
  backup:
    # https://github.com/timescale/helm-charts/blob/main/charts/timescaledb-single/docs/admin-guide.md#backups
    enabled: true
    pgBackRest:
      repo1-retention-full-type: count
      repo1-retention-diff: 14
      repo1-retention-full: 2
      repo1-type: s3
      repo1-s3-key-type: web-id # see: https://github.com/pgbackrest/pgbackrest/pull/1527
      repo1-s3-region: eu-central-1
      repo1-s3-endpoint: s3.eu-central-1.amazonaws.com

  serviceAccount:
    # A map of annotations to be set on the ServiceAccount
    annotations:
      # required to get pod env vars set my eks
      eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNTID:role/YOUR-RELEASE-backup-s3-role
```

A secret is required that holds the service account token:

```yaml
# SA AWS tokens are not autogenerated since EKS 1.24, therefor we need to create it manually
# https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
apiVersion: v1
kind: Secret
metadata:
  name: serviceaccount-secret
  annotations:
    kubernetes.io/service-account.name: "{{ .Release.Namespace }}"
type: kubernetes.io/service-account-token
data:
  # AWS EKS auto populates this secret
  # You can include additional key value pairs as you do with Opaque Secrets, this is just an example for additional values
  extra: YmFyCg==
```

**Pull request merged**
