### PR TITLE
use patroni pg_hba conf in pgBouncer

### LINKED ISSUE #234: [ISSUE] add possibility to override pg_hba of pgbouncer
**Describe the bug**
Impossible to edit pg_hba of pgBouncer. If we edit patroni pg_hba, the pg_bouncer does not use this config and we can't edit it.

**Expected behavior**
Possibility to edit pg_hba of pgBouncer or use directly the configured patroni pg_hba config in pgBouncer

**Additional context**
I have connections without ssl cert

### LINKED ISSUE #239: Possibility to override the client_tls_sslmode for pgBouncer
Hello,

It's possible to override, directly in values.yml the value of `client_tls_sslmode` for pgBouncer ? 

At this time, the only accepted requests are ssl. Even if we edit pg_hba to authorize non ssl connection. In fact, the best configuration is : 

```
client_tls_sslmode= prefer
```

OR

```
client_tls_sslmode= allow
```

### PR DESCRIPTION
**Pull request by throrin19**
Hi, I just made a PR to resolve #234 and resolve #239 : Set the pgBouncer `pg_hba.conf` directly from patroni settings to sync connections rules.

In my case, it seems the more logic to synchronize the `pg_hba.conf` of patroni to others services

### CODE REVIEW

**Comment by feikesteenbergen** [comment]
Thanks for this PR! Havingd the hba rules for pgBouncer being configurable makes a lot of sense to me.

I however don't think we want to *always* sync the Postgres pg_hba and the pgbouncer pg_hba, the currently defaults are actually very different on purpose.

We could add a `pg_hba` key in the [`pgBouncer`](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml#L389) section, where you could list all the hba rules, that would allow you to specify the hba rules.

**Comment by throrin19** [comment]
Thanks for your comments @feikesteenbergen. You are right it's munch more better to config what we want for pgBouncher.

I edited my PR based on this

**Comment by throrin19** [comment]
@feikesteenbergen any news to integrate this PR ?

**Comment by throrin19** [comment]
Any news to integrate this part in project @feikesteenbergen ?

**Review by feikesteenbergen — APPROVED** [review]

**Comment by feikesteenbergen** [comment]
@throrin19 I did some refactoring, as can be seen in #255 , basically, `pg_hba` becomes a list of entries instead of a large string.
Reason being, that the `pg_hba` for Patroni is configured as a list (which we cannot change), and having 2 ways of configuring the same thing seems confusing to me.

**Pull request merged**
